#!/bin/bash

set -eu

TOPDIR=$(dirname "$0")
TARGETDIR=$TOPDIR/quickcheck-hugs

rm -rf "$TARGETDIR"

find "$TOPDIR/src" -name '*.hs' | while read -r src; do
  tgt="$TARGETDIR/$(echo "$src" | sed "s/^$TOPDIR\/src"'//')"

  echo "Processing $src -> $tgt"

  mkdir -p "$(dirname "$tgt")"
  # If you want to switch on and off other features, look in
  # QuickCheck.cabal to see what's available, or submit a patch
  # adding a new -DNO_... flag.
  cpphs --noline -DNO_SPLITMIX -DNO_TEMPLATE_HASKELL \
    -DNO_CTYPES_CONSTRUCTORS -DNO_FOREIGN_C_USECONDS -DNO_GENERICS \
    -DNO_SAFE_HASKELL -DNO_POLYKINDS -DNO_MONADFAIL -DNO_TIMEOUT \
    -DNO_NEWTYPE_DERIVING -DNO_TYPEABLE -DNO_GADTS -DNO_TRANSFORMERS \
    -DNO_DEEPSEQ -DNO_EXTRA_METHODS_IN_APPLICATIVE \
    "$src" > "$tgt"
done

TMPDIR=$(mktemp -d)
SPLITMIX=splitmix-0.1
curl http://hackage.haskell.org/package/$SPLITMIX/$SPLITMIX.tar.gz |
  tar xzf - -C "$TMPDIR"
(pushd "$TMPDIR/$SPLITMIX";
 bash ./make-hugs.sh;
 popd) > /dev/null
mv "$TMPDIR/$SPLITMIX"/splitmix-hugs/* "$TARGETDIR"
rm -r "$TMPDIR"

echo "A Hugs-compatible version of QuickCheck is now"
echo "available in the quickcheck-hugs directory."
echo "Load it with hugs -98."
